---
- hosts: localhost
  connection: local
  roles:
    - role: nginx
      nginx_sites:
         taughtful-dev:
           - listen 80
           - server_name dev.taughtful.com
           - location / { proxy_set_header Host $host; proxy_set_header X-Forwarded-Host $host; proxy_set_header X-Forwarded-Server $host; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_pass http://dev2.dynamictivity.com; }
